.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. solbit_qt test_solbit_qt
clean: FORCE
	$(MAKE) -C .. solbit_qt_clean test_solbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_solbit_qt_check
solbit-qt solbit-qt.exe: FORCE
	 $(MAKE) -C .. solbit_qt
